#pragma once
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define COMBO_MUST_PRESS_IN_ORDER
#define COMBO_TERM 125
#define RGBLIGHT_LAYER_BLINK

#undef RGBLIGHT_DEFAULT_MODE
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 23
